name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3



    - name: Install dependencies
      run: make
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
         commit_message: auto-updated

